In [1]:
# Update sklearn to prevent version mismatches
# !pip install sklearn --upgrade

Requirement already up-to-date: sklearn in /Users/leeprout/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages (0.0)


In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
# !pip install joblib

In [1]:
import pandas as pd

# Read the CSV and Perform Basic Data Cleaning

In [2]:
df = pd.read_csv("Resources/exoplanet_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df

koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  \
0          CONFIRMED              0              0              0   
1     FALSE POSITIVE              0              1              0   
2     FALSE POSITIVE              0              1              0   
3          CONFIRMED              0              0              0   
4          CONFIRMED              0              0              0   
...              ...            ...            ...            ...   
6986  FALSE POSITIVE              0              0              0   
6987  FALSE POSITIVE              0              1              1   
6988       CANDIDATE              0              0              0   
6989  FALSE POSITIVE              0              0              1   
6990  FALSE POSITIVE              0              0              1   

      koi_fpflag_ec  koi_period  koi_period_err1  koi_period_err2  \
0                 0   54.418383     2.479000e-04    -2.479000e-04   
1                 0   19.899140     1.490000e-05    -1.490000e-05   
2                 0    1.736952     2.630000e-07    -2.630000e-07   
3                 0    2.525592     3.760000e-06    -3.760000e-06   
4                 0    4.134435     1.050000e-05    -1.050000e-05   
...             ...         ...              ...              ...   
6986              1    8.589871     1.846000e-04    -1.846000e-04   
6987              0    0.527699     1.160000e-07    -1.160000e-07   
6988              0    1.739849     1.780000e-05    -1.780000e-05   
6989              0    0.681402     2.430000e-06    -2.430000e-06   
6990              1    4.856035     6.360000e-05    -6.360000e-05   

      koi_time0bk  koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  \
0      162.513840          0.003520  ...             -81      4.467   
1      175.850252          0.000581  ...            -176      4.544   
2      170.307565          0.000115  ...            -174      4.564   
3      171.595550          0.001130  ...            -211      4.438   
4      172.979370          0.001900  ...            -232      4.486   
...           ...               ...  ...             ...        ...   
6986   132.016100          0.015700  ...            -152      4.296   
6987   131.705093          0.000170  ...            -166      4.529   
6988   133.001270          0.007690  ...            -220      4.444   
6989   132.181750          0.002850  ...            -236      4.447   
6990   135.993300          0.010800  ...            -225      4.385   

      koi_slogg_err1  koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2  \
0              0.064          -0.096     0.927          0.105         -0.061   
1              0.044          -0.176     0.868          0.233         -0.078   
2              0.053          -0.168     0.791          0.201         -0.067   
3              0.070          -0.210     1.046          0.334         -0.133   
4              0.054          -0.229     0.972          0.315         -0.105   
...              ...             ...       ...            ...            ...   
6986           0.231          -0.189     1.088          0.313         -0.228   
6987           0.035          -0.196     0.903          0.237         -0.079   
6988           0.056          -0.224     1.031          0.341         -0.114   
6989           0.056          -0.224     1.041          0.341         -0.114   
6990           0.054          -0.216     1.193          0.410         -0.137   

             ra        dec  koi_kepmag  
0     291.93423  48.141651      15.347  
1     297.00482  48.134129      15.436  
2     285.53461  48.285210      15.597  
3     288.75488  48.226200      15.509  
4     296.28613  48.224670      15.714  
...         ...        ...         ...  
6986  298.74921  46.973351      14.478  
6987  297.18875  47.093819      14.082  
6988  286.50937  47.163219      14.757  
6989  294.16489  47.176281      15.385  
6990  297.00977  47.121021      14.826  

[6991 rows x 41 columns]

In [3]:
# confirming null values have been dropped
df.isna().sum()

koi_disposition      0
koi_fpflag_nt        0
koi_fpflag_ss        0
koi_fpflag_co        0
koi_fpflag_ec        0
koi_period           0
koi_period_err1      0
koi_period_err2      0
koi_time0bk          0
koi_time0bk_err1     0
koi_time0bk_err2     0
koi_impact           0
koi_impact_err1      0
koi_impact_err2      0
koi_duration         0
koi_duration_err1    0
koi_duration_err2    0
koi_depth            0
koi_depth_err1       0
koi_depth_err2       0
koi_prad             0
koi_prad_err1        0
koi_prad_err2        0
koi_teq              0
koi_insol            0
koi_insol_err1       0
koi_insol_err2       0
koi_model_snr        0
koi_tce_plnt_num     0
koi_steff            0
koi_steff_err1       0
koi_steff_err2       0
koi_slogg            0
koi_slogg_err1       0
koi_slogg_err2       0
koi_srad             0
koi_srad_err1        0
koi_srad_err2        0
ra                   0
dec                  0
koi_kepmag           0
dtype: int64

# Select your features (columns)

In [4]:
# Set features. This will also be used as your x values.
# selected_features = df[['names', 'of', 'selected', 'features', 'here']]

# selected_features = df[['koi_period', 'koi_impact', 'koi_depth', 'koi_insol', 'koi_slogg']]

# changing approach to choosing all features by just dropping the koi_disposition column
selected_features = df.drop("koi_disposition", axis=1)
selected_features

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
0                 0              0              0              0   54.418383   
1                 0              1              0              0   19.899140   
2                 0              1              0              0    1.736952   
3                 0              0              0              0    2.525592   
4                 0              0              0              0    4.134435   
...             ...            ...            ...            ...         ...   
6986              0              0              0              1    8.589871   
6987              0              1              1              0    0.527699   
6988              0              0              0              0    1.739849   
6989              0              0              1              0    0.681402   
6990              0              0              1              1    4.856035   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
0        2.479000e-04    -2.479000e-04   162.513840          0.003520   
1        1.490000e-05    -1.490000e-05   175.850252          0.000581   
2        2.630000e-07    -2.630000e-07   170.307565          0.000115   
3        3.760000e-06    -3.760000e-06   171.595550          0.001130   
4        1.050000e-05    -1.050000e-05   172.979370          0.001900   
...               ...              ...          ...               ...   
6986     1.846000e-04    -1.846000e-04   132.016100          0.015700   
6987     1.160000e-07    -1.160000e-07   131.705093          0.000170   
6988     1.780000e-05    -1.780000e-05   133.001270          0.007690   
6989     2.430000e-06    -2.430000e-06   132.181750          0.002850   
6990     6.360000e-05    -6.360000e-05   135.993300          0.010800   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
0            -0.003520  ...             -81      4.467           0.064   
1            -0.000581  ...            -176      4.544           0.044   
2            -0.000115  ...            -174      4.564           0.053   
3            -0.001130  ...            -211      4.438           0.070   
4            -0.001900  ...            -232      4.486           0.054   
...                ...  ...             ...        ...             ...   
6986         -0.015700  ...            -152      4.296           0.231   
6987         -0.000170  ...            -166      4.529           0.035   
6988         -0.007690  ...            -220      4.444           0.056   
6989         -0.002850  ...            -236      4.447           0.056   
6990         -0.010800  ...            -225      4.385           0.054   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
0             -0.096     0.927          0.105         -0.061  291.93423   
1             -0.176     0.868          0.233         -0.078  297.00482   
2             -0.168     0.791          0.201         -0.067  285.53461   
3             -0.210     1.046          0.334         -0.133  288.75488   
4             -0.229     0.972          0.315         -0.105  296.28613   
...              ...       ...            ...            ...        ...   
6986          -0.189     1.088          0.313         -0.228  298.74921   
6987          -0.196     0.903          0.237         -0.079  297.18875   
6988          -0.224     1.031          0.341         -0.114  286.50937   
6989          -0.224     1.041          0.341         -0.114  294.16489   
6990          -0.216     1.193          0.410         -0.137  297.00977   

            dec  koi_kepmag  
0     48.141651      15.347  
1     48.134129      15.436  
2     48.285210      15.597  
3     48.226200      15.509  
4     48.224670      15.714  
...         ...         ...  
6986  46.973351      14.478  
6987  47.093819      14.082  
6988  47.163219      14.757  
6989  47.176281      15.385  
6990  47.121021      14.826  

[6991 rows x 40 c

In [5]:
# Binary Encoding for y values, koi_disposition
## use to_categorical instead of get_dummies for binary encoding

# df_binary = pd.get_dummies(df, columns=["koi_disposition"])
# df_binary

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
0                 0              0              0              0   54.418383   
1                 0              1              0              0   19.899140   
2                 0              1              0              0    1.736952   
3                 0              0              0              0    2.525592   
4                 0              0              0              0    4.134435   
...             ...            ...            ...            ...         ...   
6986              0              0              0              1    8.589871   
6987              0              1              1              0    0.527699   
6988              0              0              0              0    1.739849   
6989              0              0              1              0    0.681402   
6990              0              0              1              1    4.856035   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
0        2.479000e-04    -2.479000e-04   162.513840          0.003520   
1        1.490000e-05    -1.490000e-05   175.850252          0.000581   
2        2.630000e-07    -2.630000e-07   170.307565          0.000115   
3        3.760000e-06    -3.760000e-06   171.595550          0.001130   
4        1.050000e-05    -1.050000e-05   172.979370          0.001900   
...               ...              ...          ...               ...   
6986     1.846000e-04    -1.846000e-04   132.016100          0.015700   
6987     1.160000e-07    -1.160000e-07   131.705093          0.000170   
6988     1.780000e-05    -1.780000e-05   133.001270          0.007690   
6989     2.430000e-06    -2.430000e-06   132.181750          0.002850   
6990     6.360000e-05    -6.360000e-05   135.993300          0.010800   

      koi_time0bk_err2  ...  koi_slogg_err2  koi_srad  koi_srad_err1  \
0            -0.003520  ...          -0.096     0.927          0.105   
1            -0.000581  ...          -0.176     0.868          0.233   
2            -0.000115  ...          -0.168     0.791          0.201   
3            -0.001130  ...          -0.210     1.046          0.334   
4            -0.001900  ...          -0.229     0.972          0.315   
...                ...  ...             ...       ...            ...   
6986         -0.015700  ...          -0.189     1.088          0.313   
6987         -0.000170  ...          -0.196     0.903          0.237   
6988         -0.007690  ...          -0.224     1.031          0.341   
6989         -0.002850  ...          -0.224     1.041          0.341   
6990         -0.010800  ...          -0.216     1.193          0.410   

      koi_srad_err2         ra        dec  koi_kepmag  \
0            -0.061  291.93423  48.141651      15.347   
1            -0.078  297.00482  48.134129      15.436   
2            -0.067  285.53461  48.285210      15.597   
3            -0.133  288.75488  48.226200      15.509   
4            -0.105  296.28613  48.224670      15.714   
...             ...        ...        ...         ...   
6986         -0.228  298.74921  46.973351      14.478   
6987         -0.079  297.18875  47.093819      14.082   
6988         -0.114  286.50937  47.163219      14.757   
6989         -0.114  294.16489  47.176281      15.385   
6990         -0.137  297.00977  47.121021      14.826   

      koi_disposition_CANDIDATE  koi_disposition_CONFIRMED  \
0                             0                          1   
1                             0                          0   
2                             0                          0   
3                             0                          1   
4                             0                          1   
...                         ...                        ...   
6986                          0                          0   
6987                          0                          0   
6988                          1                          0  

# Create a Train Test Split

Use `koi_disposition` for the y values

In [5]:
X = selected_features
#y = df['koi_disposition'].values.reshape(-1, 1)
# experiment with no reshaping
y = df['koi_disposition']
print(X.shape, y.shape)

(6991, 40) (6991,)


In [6]:
# format the FALSE POSITIVE value 
mask = df["koi_disposition"] == "FALSE POSITIVE"
df.loc[mask, "koi_disposition"] = "FALSE_POSITIVE"
df["koi_disposition"]

0            CONFIRMED
1       FALSE_POSITIVE
2       FALSE_POSITIVE
3            CONFIRMED
4            CONFIRMED
             ...      
6986    FALSE_POSITIVE
6987    FALSE_POSITIVE
6988         CANDIDATE
6989    FALSE_POSITIVE
6990    FALSE_POSITIVE
Name: koi_disposition, Length: 6991, dtype: object

In [7]:
X = selected_features
y = df["koi_disposition"]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [9]:
X_train.head()

koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  koi_period  \
6122              0              0              0              0    6.768901   
6370              0              1              0              1    0.733726   
2879              1              0              0              0    7.652707   
107               0              0              0              0    7.953547   
29                0              0              0              0    4.959319   

      koi_period_err1  koi_period_err2  koi_time0bk  koi_time0bk_err1  \
6122     7.380000e-05    -7.380000e-05   133.077240          0.008440   
6370     6.060000e-06    -6.060000e-06   132.020050          0.007950   
2879     6.540000e-05    -6.540000e-05   134.460380          0.006190   
107      1.910000e-05    -1.910000e-05   174.662240          0.001820   
29       5.150000e-07    -5.150000e-07   172.258529          0.000083   

      koi_time0bk_err2  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \
6122         -0.008440  ...            -171      4.327           0.153   
6370         -0.007950  ...            -175      4.578           0.033   
2879         -0.006190  ...            -189      4.481           0.050   
107          -0.001820  ...             -85      4.536           0.056   
29           -0.000083  ...             -77      4.359           0.110   

      koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \
6122          -0.187     1.125          0.310         -0.207  294.40472   
6370          -0.187     0.797          0.211         -0.056  284.50391   
2879          -0.200     0.963          0.290         -0.097  295.50211   
107           -0.016     0.779          0.023         -0.049  291.15878   
29            -0.110     1.082          0.173         -0.130  292.16705   

            dec  koi_kepmag  
6122  39.351681      14.725  
6370  42.463860      15.770  
2879  38.983540      13.099  
107   40.750271      15.660  
29    48.727589      15.263  

[5 rows x 40 columns]

In [10]:
y.value_counts()

FALSE_POSITIVE    3504
CONFIRMED         1800
CANDIDATE         1687
Name: koi_disposition, dtype: int64

In [30]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from tensorflow.keras.utils import to_categorical

In [38]:
# experimenting with scaler before label-encoding
# following example from Voice_Recognition Activity 
# scaler = MinMaxScaler()
# standard scaler is st. deviation, MinMax scaler is -1, 1
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
# y_scaler = MinMaxScaler().fit(y_train)

In [39]:
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)
print(label_encoder.classes_)
encoded_y_train

['CANDIDATE' 'CONFIRMED' 'FALSE_POSITIVE']


array([0, 2, 2, ..., 2, 2, 2])

In [32]:
y_train_categorical = to_categorical(encoded_y_train)
print(y_train_categorical)
y_train_categorical.dtype

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


dtype('float32')

# Pre-processing

Scale the data using the MinMaxScaler and perform some feature selection

In [50]:
# Scale your data
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()
# X_scaler = MinMaxScaler().fit(X_train)
# y_scaler = MinMaxScaler().fit(y_train)

In [52]:
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)
# y_train_scaled = y_scaler.transform(y_train)
# y_test_scaled = y_scaler.transform(y_test)

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [16]:
# Create model and add layers
# model_1 = Sequential()
# model_1.add(Dense(units=100, activation='relu', input_dim=20))
# model_1.add(Dense(units=100, activation='relu'))
# model_1.add(Dense(units=2, activation='softmax'))

In [17]:
# Compile and fit the model
# model_1.compile(optimizer='adam',
#               loss='categorical_crossentropy',
#               metrics=['accuracy'])

In [18]:
# model_1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               2100      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 202       
Total params: 12,402
Trainable params: 12,402
Non-trainable params: 0
_________________________________________________________________


In [34]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.8541189931350115

In [37]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=500)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9010297482837528

In [24]:
sorted(zip(clf.feature_importances_, selected_features), reverse=True)

[(0.19498480426684975, 'koi_fpflag_nt'),
 (0.1832237219933048, 'koi_fpflag_co'),
 (0.17331823962024664, 'koi_fpflag_ss'),
 (0.13682040843498847, 'koi_model_snr'),
 (0.02983543937903136, 'koi_fpflag_ec'),
 (0.025179036544701158, 'koi_impact'),
 (0.01583973593111533, 'dec'),
 (0.013356673194549714, 'koi_srad_err1'),
 (0.013138608611488623, 'koi_prad'),
 (0.012431859315157077, 'koi_time0bk_err1'),
 (0.012104910407803787, 'koi_depth_err1'),
 (0.011650983616781439, 'koi_duration'),
 (0.011251247794677798, 'koi_steff_err2'),
 (0.010439725819324563, 'koi_insol_err1'),
 (0.010285829353737815, 'koi_time0bk'),
 (0.010254598881981465, 'koi_steff_err1'),
 (0.01023473097987214, 'koi_duration_err2'),
 (0.009802246665019575, 'ra'),
 (0.00923203139422918, 'koi_impact_err1'),
 (0.008757054857363408, 'koi_period'),
 (0.007811359706269514, 'koi_prad_err1'),
 (0.007082240708622112, 'koi_depth'),
 (0.006976429178183775, 'koi_slogg_err2'),
 (0.00693341028412862, 'koi_period_err2'),
 (0.006778928737731482, '

In [28]:
sorted(zip(rf.feature_importances_, selected_features), reverse=True)

[(0.10681120856224399, 'koi_fpflag_co'),
 (0.09954148503289088, 'koi_fpflag_nt'),
 (0.06989551275073916, 'koi_fpflag_ss'),
 (0.05535589706436463, 'koi_model_snr'),
 (0.04190182010374615, 'koi_prad'),
 (0.038626579733041656, 'koi_steff_err1'),
 (0.036170726858770215, 'koi_prad_err2'),
 (0.03484942431091892, 'koi_fpflag_ec'),
 (0.03287808806367033, 'koi_duration_err2'),
 (0.032814215541504904, 'koi_prad_err1'),
 (0.032410917970812574, 'koi_duration_err1'),
 (0.0265557983661149, 'koi_steff_err2'),
 (0.024784094330596716, 'koi_time0bk_err1'),
 (0.022372064034618954, 'koi_time0bk_err2'),
 (0.02224555665212274, 'koi_duration'),
 (0.021720879807712964, 'koi_period'),
 (0.02122792734672371, 'koi_depth'),
 (0.01823744948244108, 'koi_impact'),
 (0.017728129800960817, 'koi_insol_err1'),
 (0.017502616975482797, 'koi_period_err2'),
 (0.016103611837065056, 'koi_period_err1'),
 (0.015261562567564, 'koi_insol_err2'),
 (0.015105073157460673, 'koi_teq'),
 (0.015084719664819368, 'koi_insol'),
 (0.0136728

# Train the Model



In [26]:
print(f"Training Data Score: {clf.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {clf.score(X_test_scaled, y_test)}")

Training Data Score: 0.5632271600228876
Testing Data Score: 0.5789473684210527


# Hyperparameter Tuning

Use `GridSearchCV` to tune the model's parameters

In [ ]:
# Create the GridSearchCV model
# Do a GridSearch on two classifiers and compare them

In [ ]:
# Train the model with GridSearch

In [ ]:
print(grid2.best_params_)
print(grid2.best_score_)

# Save the Model

In [ ]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'your_name.sav'
joblib.dump(your_model, filename)